"""
GET /api/home  —  single endpoint that feeds the home screen.

Returns:
  - steps_yesterday, steps_week_total, steps_daily_goal, steps_pct (progress vs goal)
  - rank (in active step challenge), rank_change
  - habits_today  (challenge_id, completed_count, total_count, day_number)
  - habit_streak  (current, longest)
  - ai_insight    (badge, headline, detail)  — generated by Claude
"""
from datetime import date, timedelta

from fastapi import APIRouter, Depends
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth.deps import get_current_user
from app.db.deps import get_db
from app.models import User
from app.services.ai_insight import get_home_insight

router = APIRouter(prefix="/api/home", tags=["home"])


@router.get("")
async def home(
    db: AsyncSession = Depends(get_db),
    user: User = Depends(get_current_user),
):
    today = date.today()
    yesterday = today - timedelta(days=1)
    uid = str(user.id)

    # ── Steps ────────────────────────────────────────────────────────────────
    steps_row = await db.execute(text("""
        SELECT
            COALESCE(SUM(CASE WHEN day = :yesterday THEN steps ELSE 0 END), 0) AS steps_yesterday,
            COALESCE(SUM(CASE WHEN day = :today    THEN steps ELSE 0 END), 0)  AS steps_today
        FROM daily_steps
        WHERE user_id = :uid
    """), {"uid": uid, "yesterday": yesterday, "today": today})
    sr = steps_row.mappings().first() or {}
    steps_yesterday = int(sr.get("steps_yesterday") or 0)
    steps_today     = int(sr.get("steps_today") or 0)

    # ── Active step challenge: daily target, rank, rank_change ───────────────
    challenge_row = await db.execute(text("""
        SELECT
            c.id                                AS challenge_id,
            c.title                             AS challenge_title,
            COALESCE(cp.selected_daily_target, 8000) AS daily_target,
            cp.previous_rank                    AS rank,
            cp.challenge_current_streak         AS step_streak
        FROM challenge_participants cp
        JOIN challenges c ON c.id = cp.challenge_id
        WHERE cp.user_id = :uid
          AND c.status   = 'active'
          AND c.end_date >= :today
          AND cp.left_at IS NULL
        ORDER BY c.end_date DESC
        LIMIT 1
    """), {"uid": uid, "today": today})
    cr = challenge_row.mappings().first()

    daily_target  = int(cr["daily_target"]) if cr else 8000
    step_challenge_id = cr["challenge_id"] if cr else None
    rank          = int(cr["rank"]) if cr and cr["rank"] else None
    step_streak   = int(cr["step_streak"]) if cr and cr["step_streak"] else 0
    steps_pct     = min(round(steps_today / daily_target * 100) if daily_target else 0, 100)

    # Live rank (for rank_change vs previous_rank snapshot)
    rank_change = None
    if step_challenge_id and rank is not None:
        ch_dates = await db.execute(text("""
            SELECT start_date, LEAST(end_date, :today) AS end_cap
            FROM challenges WHERE id = :cid
        """), {"cid": step_challenge_id, "today": today})
        cd = ch_dates.mappings().first()
        if cd:
            live_row = await db.execute(text("""
                WITH totals AS (
                    SELECT cp.user_id,
                           COALESCE(SUM(ds.steps), 0) AS total_steps
                    FROM challenge_participants cp
                    LEFT JOIN daily_steps ds
                        ON ds.user_id = cp.user_id
                        AND ds.day   >= :start
                        AND ds.day   <= :end
                    WHERE cp.challenge_id = :cid AND cp.left_at IS NULL
                    GROUP BY cp.user_id
                )
                SELECT ROW_NUMBER() OVER (ORDER BY total_steps DESC) AS live_rank
                FROM totals
                WHERE user_id = :uid
            """), {
                "cid": step_challenge_id,
                "start": cd["start_date"],
                "end": cd["end_cap"],
                "uid": uid,
            })
            live_rank = live_row.scalar()
            if live_rank:
                rank_change = rank - int(live_rank)  # positive = moved up

    # ── Habits ───────────────────────────────────────────────────────────────
    habit_row = await db.execute(text("""
        SELECT
            hc.id                   AS challenge_id,
            hc.started_at,
            hc.ends_at,
            COUNT(DISTINCT hcm.id)  AS total_habits,
            COALESCE(SUM(CASE WHEN dl.logged_date = :today AND dl.completed THEN 1 ELSE 0 END), 0)
                                    AS done_today
        FROM habit_challenges hc
        JOIN habit_commitments hcm ON hcm.challenge_id = hc.id
        LEFT JOIN daily_logs dl ON dl.commitment_id = hcm.id
        WHERE hc.user_id = :uid AND hc.status = 'active'
        GROUP BY hc.id
        LIMIT 1
    """), {"uid": uid, "today": today})
    hr = habit_row.mappings().first()

    habits_today = None
    habit_streak = user.global_current_streak or 0
    if hr:
        total_habits = int(hr["total_habits"])
        done_today   = int(hr["done_today"])
        day_number   = (today - hr["started_at"]).days + 1 if hr["started_at"] else 1
        habits_today = {
            "challenge_id":    hr["challenge_id"],
            "day_number":      day_number,
            "total_days":      (hr["ends_at"] - hr["started_at"]).days + 1 if hr["started_at"] else 21,
            "completed_count": done_today,
            "total_count":     total_habits,
            "all_done":        done_today >= total_habits,
        }

    # ── AI insight ────────────────────────────────────────────────────────────
    insight = await get_home_insight(db, str(uid))

    return {
        "steps": {
            "yesterday":   steps_yesterday,
            "today":       steps_today,
            "daily_target": daily_target,
            "pct":         steps_pct,
            "step_streak": step_streak,
        },
        "challenge": {
            "id":          step_challenge_id,
            "rank":        rank,
            "rank_change": rank_change,
        },
        "habits": habits_today,
        "habit_streak": habit_streak,
        "ai_insight": insight,
        "user": {
            "name": user.name,
            "profile_pic_url": user.profile_pic_url,
        },
    }
